{% set name = "analytics-python" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/segment-{{ name }}/segment-{{ name }}-{{ version }}.tar.gz
  sha256: ce6b3b4387ec9ebc5b55842c44d7dd63b4d4b0b8188e268c4492f909e5eeeed8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - requests >=2.7,<3
    - backoff >=2.1,<3
    - python-dateutil >=2.2,<3
    - pyjwt >=2.8,<3

test:
  source_files:
    - segment/analytics/test
  imports:
    - segment.analytics
    - segment.analytics.test
  commands:
    - pip check
    - pytest -v segment/analytics/test
  requires:
    - pip
    - pytest
    - mock
    - cryptography

about:
  home: https://github.com/segmentio/analytics-python
  summary: The hassle-free way to integrate analytics into any python application.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: analytics-python is a python client for [Segment](https://segment.com)
  doc_url: https://segment.com/libraries/python
  dev_url: https://github.com/segmentio/analytics-python

extra:
  recipe-maintainers:
    - BrentDorsey
    - sugatoray
