travis:
  secure:
    BINSTAR_TOKEN: fVawtMfD6krb7kQkFJRozeuDxW1Z22ZVvG0Tae+3RF4MJFstV0NQ3vJk5inIyiMQS1dMUGboYQdHON9aBw3CR1gL8G9TgXe8HtE8ugHGgkNqQMUbeFuE1PC1QhSm/WmiQDt3ujXtpFrDAVacbkDHLcdPJcYadYrMf7hKmyQF5WZDlLhgzbAG8/NWApZlWXDuiGxBylR2VLZawOk1wvhdyZqQ2pwqF7jBj3wdccDFJVodeVs6XrkFODhtmpWbnaCp3xJjhdLamMrB6e6QAs98w+sp2bUORW6QQlv9TI+7XAY4pOIaJz9pwRHEL9tXjytrRCurjTCb5vv4Q0ZC5F8GNlMT8hCq7dJYjYa0yyj2IkhFsQnINX046O7qfKEE3ALofq6S0bbePoBPV2uCuYSPc5C+FgFEcZL7+cZGZY1N5mBVTKWlXg2G6rs+XA3SAmHacVSWkvmm2ys+nizoe9rIVaMGtD/tUq5zy22ZRASzXxDf4z5XSKPBV0HdVE0GMwVlmL0qYDy/QBXhf/bVyHo1o5rBmif1NzFIyCVDFnMxjnS3WOP0EVg3OGOJ3aGrDsEYSYKxk/ukYMIat1BIKyCyistyPnh8LuyU6O0ZS0SbpJqO2o7y6yTdJU3fx/T770VeUr91F+QpCLi2R1PYJaFFyZNyBn/CAQap9RAvUJfnExE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
